# Generated by Django 5.0.7 on 2024-11-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questaosimulado',
            unique_together={('simulado', 'ordem', 'questao')},
        ),
    ]
