# Generated by Django 5.0.7 on 2024-11-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questaosimulado_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_a',
            new_name='alternativa_A',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_b',
            new_name='alternativa_B',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_c',
            new_name='alternativa_C',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_d',
            new_name='alternativa_D',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_e',
            new_name='alternativa_E',
        ),
    ]
