# Generated by Django 5.0.7 on 2024-11-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_alternativa_a_questao_alternativa_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_A',
            new_name='alternativa_a',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_B',
            new_name='alternativa_b',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_C',
            new_name='alternativa_c',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_D',
            new_name='alternativa_d',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_E',
            new_name='alternativa_e',
        ),
    ]
