# Generated by Django 5.0.7 on 2024-11-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_alternativa_a_questao_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questaosimulado',
            unique_together={('simulado', 'ordem'), ('simulado', 'questao')},
        ),
    ]
